/**
 * The review wall, one copy for every landing page (Hormozi teardown edit #2, Jonny 2026-10-06).
 *
 * acquisition.com/workshop shows 50 reviews under "Filter to your world", each card marked as a
 * verified Google review. Music and Mastery has no Google reviews of its own, so Jonny's call
 * (2026-10-06) is up to 50 reviews of Mountain City Music Co., with the same-company caveat on
 * every block. The caveat lives in each page's static header AND on every card, so a card read
 * on its own (or screenshotted) still says whose review it is.
 *
 * Source: data/google-reviews-2026-10-06.json, all 65 reviews read from Google on 2026-10-06.
 * The array below is GENERATED by scripts/build-reviews.py, never edited by hand, and
 * scripts/check-reviews.mjs (npm test) proves each quote is the review exactly, or its leading
 * whole sentences.
 *
 * The 15 of 65 left out, and why:
 *   - no words to quote: Sarah R., Linda J. (stars only)
 *   - words we would have to guess at: Raquel U. ("mountain cutting music"), Grill N. ("I would
 *     decorate definitely recommend"), Suo J.
 *   - would read as staff: Alli P. and Javien M. share first names with instructors
 *   - not a student yet when written: Gracy ("I will be taking Vocal lessons")
 *   - em dash in the opening lines, so no clean leading excerpt: Tershama H.
 *   - promises we do not make: Tyra T. ("always offering great deals")
 *   - thin, the cut to 50: Jay, Josue R., Angela H., Brittany S., Jen C.
 *
 * Page contract: <div class="rv-wall" data-review-wall data-instrument="piano"></div>.
 * data-instrument (optional) puts that instrument's reviews first.
 *
 * /js/ is served immutable for a year, so every page loads this as reviews.js?v=<first 10 hex of
 * its SHA-256>. npm test fails if any page's ?v= does not match the file.
 *
 * All 50 show at once (Jonny 2026-10-07: no "show all" button); the filter narrows them.
 *
 * GA4: rv_filter (which chip), rv_read_more.
 */
(function () {
  var REVIEWS = [
    // BEGIN GENERATED by scripts/build-reviews.py
    {"n": "Laurissa W.", "q": "I highly recommend Mountain City Music! My kids were at the point where they wanted to quit guitar, and since switching, the difference has been amazing. They actually want to practice, play songs together, and genuinely enjoy guitar again. Bryce has been an incredible instructor and, in such a short time, has really gotten to know each of them and how to help them improve individually. The convenience of having lessons right in our home is a huge plus, and the professionalism and communication from the company have been wonderful. We couldn’t be happier with our experience!", "a": "", "i": "guitar"},
    {"n": "Heather C.", "q": "3 weeks in and Jonny has totally unlocked my 6 yr old's love of music. He's gone from total beginner at piano to learning a couple songs and begging to practice every day. Jonny makes it super fun and rewarding for the kids so even little guys look forward to their lessons. Wish I could give more than 5 stars!", "a": "young", "i": "piano"},
    {"n": "Kimberly M.", "q": "My daughter has been having a great time working with Mountain City Music Company. She is new to piano lessons and is so excited each week to work with her teacher. It has been a very positive experience. I am also grateful that this is a company still willing to travel to people's homes. It is easy to work piano lessons into our schedule this way.", "a": "", "i": "piano"},
    {"n": "Ashly B.", "q": "Jonny is awesome! My teenager wanted to take piano lessons, but wanted a more private setting. Mountain City Music provides us with exactly that! During the first session Jonny evaluated my son, and he was extremely kind. I thought my son was horrible, but to hear Jonny say he was doing a great job, was so encouraging! We're excited to see all the skills he learns over the next year!", "a": "teen", "i": "piano"},
    {"n": "Sammy R.", "q": "Ive been taking these classes for a few weeks and I can say I have gotten so much better at guitar. The classes aren't boring, they're really simple, and they definitely help me improve in my guitar skills. The classes are pretty flexible with your schedule which is great for someone like me who's constantly busy. Definitely 5 star worthy!", "a": "adult", "i": "guitar"},
    {"n": "Melissa G.", "q": "My family has been with Mountain City Music Company for one school year now and I have been so impressed with them. My son takes guitar lessons with Connor and my daughter takes piano lessons with Frank. I love that the instructors come to our home for lessons. Both Connor and Frank have been great instructors. They are encouraging and know how to engage my children in their lessons. Both of my kids have had private lessons before we joined Mountain City, but never have they grown so fast in their knowledge, skill, and passion for music as they have since joining this school. The founder of the company, Jonny Dolan, has also been terrific to work with. His business is an asset to our community. It is evident that he is a talented professional and really cares about his students. I highly recommend Mountain City Music Company. They are the best!", "a": "", "i": "guitar piano"},
    {"n": "Rachel M.", "q": "I contacted Mountain City Music Co. for voice lessons for my high-school son who got a part in a school musical and had no previous vocal training. We booked Jonny for several lessons and I am so happy we did!\nIn a short time, Jonny’s instruction addressed and yielded improvements in posture, breathing, technique for high notes, and general vocal health. My son is feeling and sounding more confident with the vocal techniques he has learned.\nI highly recommend Mountain City Music Co. for lessons. The website is easy to use and book through. Jonny is a knowledgeable, friendly, and exceptional music instructor, and will travel to you. If you or your student have ever thought about private voice lessons, I think you’ll find Mountain City Music Co. to be an excellent instructional resource!", "a": "teen", "i": "voice"},
    {"n": "Jennifer S.", "q": "Mountain City Music is the perfect fit for our busy family. With so many activities already filling our schedules, it’s one less drive to worry about. It helps me so much! Having piano lessons in our home has been such a welcome convenience and gives me a much-needed break from constantly shuttling my kids around town.", "a": "", "i": "piano"},
    {"n": "Emily K.", "q": "Mountain City Music is a great company, if you are looking for music lessons. It is well organized and well operated. My son’s guitar instructor teaches him the fundamentals of music as well and working on songs my son specifically wants to learn. My son really looks forward to his lesson. And it’s very convenient that they come to your home.", "a": "", "i": "guitar"},
    {"n": "Yessenia", "q": "Love this company and how much my daughter has progressed! She is 5 but started when she was 4. Her piano teacher Frank is amazing she is learning so quickly and he is constantly affirming her and being so positive giving her that confidence she needs but also giving her areas to practice that helps so much for the week to come. Enjoying seeing my daughter’s growth at this company!", "a": "young", "i": "piano"},
    {"n": "Cristal C.", "q": "Bryce, my son’s guitar instructor, is professional and at the same time is able to connect with my 13 year old boy who is a beginner at playing an electric guitar. I love how Bryce ensures that any song that is being taught is something my son is interested in. My son has been receiving lessons for about 4 months. I am very satisfied with the lessons. The instructor comes to our home on a weekly basis for one hour. My son is also practicing on his own time and I can hear improvement each time. I am also very grateful with the instructor because he accommodates when we are unable to meet at the schedule time, we are always able to reschedule and make up for that class. I also greatly appreciate the instructor’s advice and input regarding guitar material because I asked the parent do not know anything about guitar.", "a": "teen", "i": "guitar"},
    {"n": "Jane A.", "q": "The owner, Johnny, is easy to reach and was very helpful from the start. Johnny answered all my questions, which was especially helpful since we're new to the high desert area. My daughter has been taking singing classes, and her instructor, Caitlynn, is incredibly patient. Caitlynn is always on time and has a lovely voice. We recently added piano lessons in, and she’s been great with my daughter. The progress my daughter has made since starting these lessons is remarkable, and she always looks forward to her classes. I love how these classes are at home, making it so convenient for us! The overall experience with Mountain City Music Company has been wonderful, and I highly recommend them to anyone looking for quality music instruction!", "a": "", "i": "voice piano"},
    {"n": "Ricardo P.", "q": "Have had a great experience so far with vocal lessons. Mr Dolan is a great guy and very clear when explaining. Very structured and profesional. Im excited to keep learning from him!", "a": "adult", "i": "voice"},
    {"n": "Shakira S.", "q": "My daughter has been thriving in only 3 short sessions! She has already learned one song and moving on to the next! Teacher Johnny has been very gentle and very at her pace. I love to see her confidence get bigger and bigger after each session!", "a": "", "i": ""},
    {"n": "Breanna Q.", "q": "Jonny has excellent teaching skills, his friendly personality and positive attitude really makes our family comfortable. I appreciated how he took the time to get to know her as a person and tailor the lesson to my specific goals and music interests. Our 14 year old looks forward to her guitar lesson all week long!", "a": "teen", "i": "guitar"},
    {"n": "Jessica S.", "q": "This is our first year using Mountain City Music Company. My two boys are receiving piano lessons from Raymond. We're only three lessons in and they both have learned so much! From the very first lesson they were taught the basics and were able to play a simple song. So far up to this point we are satisfied and thankful :)", "a": "", "i": "piano"},
    {"n": "Owen L.", "q": "My daughter is only 4 years old but I’ve been looking for lessons in our area for a while, I was so excited when saw a flyer for Mountain City Music at her elementary school. I gave them a call and he fit us into his schedule right away! The first lesson she was so shy and didn’t want to sing for him, the next week he adjusted his technique (started giving her m&m’s as a reward ) and now she’s really opened up to him, she’s learning new songs and most importantly having a lot of fun while doing it. I couldn’t be happier with Jonny!", "a": "young", "i": "voice"},
    {"n": "Gabi T.", "q": "I am extremely impressed with how excellent these private music lessons are. I literally recommend them to everyone I know and anyone I just met looking for an amazing vocal or piano teacher. My kids (6y/o and 10y/o,) are a bit over active at times, but Johnny has done such an exceptional job keeping them on task and intrigued to keep going. I love the fact that he gives them a variety of options with the songs they would like to learn and the way to read music notes.", "a": "young", "i": ""},
    {"n": "Maressah C.", "q": "Best experience I've had with guitar lessons. I have an awesome teacher and I've been learning a lot. Coming from a beginner guitar player, I highly recommend coming to Mountain City Music Company if you're trying to learn!", "a": "adult", "i": "guitar"},
    {"n": "Sarah N.", "q": "Mountain City Music has been great! My daughter has taken both guitar lessons and voice lessons with their instructors. They are knowledgeable and give helpful tips that have helped my daughter improve immensely. The instructors come to our home, which is so convenient. I love that they work with our charter school. I can’t recommend them enough!", "a": "", "i": "guitar voice"},
    {"n": "Tammy F.", "q": "My child has been receiving voice lessons from Jonny Dolan for several months now, and in that time we've seen huge improvements in range, musicianship, and breath control. The patience and encouragement he shows students is incredible. I would definitely recommend this company for anyone looking to improve their abilities!", "a": "", "i": "voice"},
    {"n": "Angie G.", "q": "We just love Mountain City Music Company! Johnny is an awesome teacher! He has really shown and taught my children in a way that they understand and is helpful to them. We love the flexibility and availability that he has offered us and the fact that it is personal. I would highly recommend Mountain City Music Company to anyone for their music needs. I have a son who is learning guitar and a daughter who is learning piano this year but we are looking forward to adding voice lessons as well. You can't go wrong with choosing Johnny and his company!", "a": "", "i": "guitar piano"},
    {"n": "Annia V.", "q": "Working with Mountain City Music Company has been an absolutely wonderful experience! We’ve had the pleasure of working with Frank, and Caitlynn. Both of them are punctual, professional, and genuinely respectful. What stands out the most is their love and patience with my kids. They make every lesson encouraging, and engaging. It’s clear they truly care about their students’ growth and confidence in music. We couldn’t recommend them more!", "a": "", "i": ""},
    {"n": "RaQuel F.", "q": "I absolutely love the work this company does! My instructor is incredibly helpful when it comes to explaining the technical side of voice, he is always open to hearing my ideas (and explaining why I shouldn’t pursue certain songs if they aren’t helping me towards my goal) they are very open and transparent when it comes to my faults with never being harsh or discouraging me! Great company!", "a": "adult", "i": "voice"},
    {"n": "Laia L.", "q": "My granddaughter’s guitar teacher is excellent. She is learning beginning guitar and has never had guitar lessons before. The teacher is very knowledgeable, an excellent musician who is wisely tailoring the lessons to include the type of music she likes. As a result she is motivated to learn and practice. The teacher is very patient and approachable. He is always on time and a pleasure to have in our home for the lesson. I strongly recommend mountain city music company for lessons. We could not be happier with the lessons, or the close communication between the guitar instructor, the student, and our family. We decided to schedule the 45 minute lessons so she has time to focus on the instructions but not too long so she gets tired. It was a good decision. Strongly recommend this vendor!!", "a": "", "i": "guitar"},
    {"n": "Grisiel R.", "q": "Our experience with Johnny and his company has been extraordinary he is a great teacher I would highly recommend him to anyone with small kids he does so great he is so patient and so kind and just an amazing person overall my son has learned so much from knowing nothing at all he can now carry a tune and play few notes from various songs. Like every thing takes time but in such a short time I've seen so much progress.", "a": "young", "i": ""},
    {"n": "Eva M.", "q": "I came across this company through my child's charter school website and have been using them for a few months now. Our instructor Jonny is awesome! We use him for piano lessons but he teaches many other things. He is very friendly and flexible with our schedule. After a few lessons, he can begin to understand how one learns and has figured out the best way for my child to understand what he is teaching. He is a super cool guy which my daughter enjoys learning from. The best part is that he comes to you which is nice for people with busy schedules. I would definitely recommend!", "a": "", "i": "piano"},
    {"n": "Brooke P.", "q": "Caitlynn has been amazing! It is so comfortable and convenient to have someone come to house. My daughter enjoys each lesson. It has made a huge difference in her confidence and ability to use her voice.\n👍👍👍👍👍", "a": "", "i": "voice"},
    {"n": "Michael T.", "q": "I’m so very pleased with Mountain City Music Co. My granddaughter is very excited about her guitar lessons! Bryce showed her ways to make exploring the guitar fun. She’s been practicing!!", "a": "", "i": "guitar"},
    {"n": "Julissa B.", "q": "We absolutely love Johnny from mountain city music. He is such a great instructor who is very patient with my little one. She has learned so much in such a short time! He is very focused on lessons and improvements and we love that. Thank you Johnny!! 🥳", "a": "young", "i": ""},
    {"n": "Angelica K.", "q": "Mountain City Music company is very convenient, they come to your house and work around your schedule. Our piano teacher - Caitlynn, is patient and kind with my daughter. My daughter’s piano skills improve every week. Definitely would recommend to others looking for music lessons.", "a": "", "i": "piano"},
    {"n": "Samantha A.", "q": "My son looks forward to and enjoys his weekly guitar lessons. His instructor Bryce is always on time and conducts himself in a very professional manner. As a teacher, he communicates clearly and is very patient. Our experience with Mountain City Music has been nothing but positive, and would recommend them highly.", "a": "", "i": "guitar"},
    {"n": "Andrew W.", "q": "Love this company, the owner Jonny is super easy to work with and he answered all my questions and got me an my brother setup with Davey, who's been amazing and has completely tailored the lessons to our needs as independent musicians. Has been nothing but a great experience definitely go with them.", "a": "adult", "i": ""},
    {"n": "Diana M.", "q": "My son was assessed first then lessons were adjusted to his needs, that's something that I loved. Mr.Dolan has worked with our schedules and it has made it so easier for our family. My son has enjoyed his guitar lessons.\nI truly recommend it!", "a": "", "i": "guitar"},
    {"n": "Jackie S.", "q": "This company is the best - my 10 year old son started his sessions at the beginning of October. He has retained so much knowledge and enthusiasm for his guitar lessons with Bryce. Something he looks forward to every week. Thank you Johnny and Bryce", "a": "", "i": "guitar"},
    {"n": "Vanessa G.", "q": "It has been an absolute joy finding such a spectacular music/singing lesson program for my daughter. Her instructor is just amazing and so kind. Every person I have dealt with in this company has been nothing but patient, helpful and so professional. Such a great opportunity for anyone who is looking to expand in their musical journey.", "a": "", "i": "voice"},
    {"n": "Michelle B.", "q": "My son has started taking guitar lessons from Mountain City Music Company. The instructor, Johnny, is amazing. My son has already picked up so much from the 2 lessons he has had. I highly recommend this place. Easy to schedule, easy to work with, friendly and encouraging.", "a": "", "i": "guitar"},
    {"n": "Victoria H.", "q": "Our piano instructor is so talented and great with our 10yr old. He's learned so much and looks forward to practicing and his lessons.", "a": "", "i": "piano"},
    {"n": "Bradley H.", "q": "Jonny is really cool and as an independent artist Davey is great at teaching me how to use my vocals and at helping me improve upon my own original songs", "a": "adult", "i": "voice"},
    {"n": "Karla S.", "q": "My children are loving their vocal and guitar lessons. The instructors are very patient and knowledgeable. I would recommend Mountain City in a heartbeat!", "a": "", "i": "guitar voice"},
    {"n": "Ashley H.", "q": "We are loving our lessons through Mountain City Music! My 2 kids are learning Guitar and Piano and they love the lessons and are learning so much.", "a": "", "i": "guitar piano"},
    {"n": "Susan W.", "q": "Stellar!!! My daughter has improved considerably by working with Mr. Dolan. He is patient and wonderfully knowledgeable. THEE best vocal/music teacher.\nThank you, thank you for all you do!!", "a": "", "i": "voice"},
    {"n": "Donna F.", "q": "We are very happy with mountain City Music Company. The communication with the school as well as the instructor has been good. They have been supportive with our needs. My daughters instructor has been very informative as well as encouraging so she's been looking forward to each lesson.", "a": "", "i": ""},
    {"n": "Ana C.", "q": "I am so grateful to have found Mountain City Music. My kid's instructor, Marcello, has been patient with my kids as they learn their instrument of choice. His professionalism and patience is more than I could ask for.", "a": "", "i": ""},
    {"n": "Joanna B.", "q": "We love how comfortable and personal the voice lessons are. Ally is amazing with children and very communicative about lessons and plans.", "a": "", "i": "voice"},
    {"n": "Julie M.", "q": "My kiddos have been getting lessons through Mountain City Music Co for a few months now and they love it! Ethan has been great with them and I’m pleased with their progress so far.", "a": "", "i": ""},
    {"n": "Bianca", "q": "My son has been loving guitar lessons, I recommend this company. Very flexible and they come to you. Great service!", "a": "", "i": "guitar"},
    {"n": "Brooklynn G.", "q": "Johnny has been amazing. Our daughter has already shown much improvement & enjoys the class.", "a": "", "i": ""},
    {"n": "Sheila J.", "q": "The kids absolutely love their teacher and they look forward to their class every week.", "a": "", "i": ""},
    {"n": "Amber", "q": "My son Matthew has had nothing but wonderful things to say about his private lessons. We look forward to continuing our time with mountain city music company!", "a": "", "i": ""}
    // END GENERATED
  ];

  var FILTERS = [
    { key: 'all', label: 'All' },
    { key: 'young', label: 'Young kids', test: function (r) { return r.a === 'young'; } },
    { key: 'teen', label: 'Teens', test: function (r) { return r.a === 'teen'; } },
    { key: 'adult', label: 'Adults', test: function (r) { return r.a === 'adult'; } },
    { key: 'piano', label: 'Piano', test: function (r) { return has(r, 'piano'); } },
    { key: 'guitar', label: 'Guitar', test: function (r) { return has(r, 'guitar'); } },
    { key: 'voice', label: 'Voice', test: function (r) { return has(r, 'voice'); } }
  ];
  var NOUN = { young: 'reviews about young kids', teen: 'reviews about teens', adult: 'reviews from adult students',
    piano: 'piano reviews', guitar: 'guitar reviews', voice: 'voice and singing reviews' };

  function has(r, inst) { return (' ' + r.i + ' ').indexOf(' ' + inst + ' ') !== -1; }
  function track(name, params) {
    try { if (typeof gtag === 'function') gtag('event', name, params || {}); } catch (e) {}
  }
  function el(tag, cls, text) {
    var e = document.createElement(tag);
    if (cls) e.className = cls;
    if (text != null) e.textContent = text;
    return e;
  }

  function card(r) {
    var fig = el('figure', 'rv-card');
    var stars = el('div', 'rv-card-stars', '★★★★★');
    stars.setAttribute('aria-label', '5 out of 5 stars');
    fig.appendChild(stars);
    var quote = el('blockquote', 'rv-quote');
    r.q.split(/\n\s*\n/).forEach(function (para) { quote.appendChild(el('p', null, para)); });
    fig.appendChild(quote);
    var more = el('button', 'rv-more', 'Read the whole review');
    more.type = 'button';
    more.hidden = true;
    more.addEventListener('click', function () {
      fig.classList.add('is-open');
      more.hidden = true;
      track('rv_read_more', { reviewer: r.n });
    });
    fig.appendChild(more);
    var cap = el('figcaption', 'rv-cap');
    cap.appendChild(el('span', 'rv-name', r.n));
    cap.appendChild(el('span', 'rv-src', 'Google review of Mountain City Music Co.'));
    fig.appendChild(cap);
    return { node: fig, more: more, quote: quote };
  }

  function mount(wall) {
    var inst = wall.getAttribute('data-instrument') || '';
    var list = REVIEWS.slice();
    if (inst) {
      // Stable: matching reviews first, each group in the curated order.
      list = list.filter(function (r) { return has(r, inst); })
        .concat(list.filter(function (r) { return !has(r, inst); }));
    }

    var bar = el('div', 'rv-filters');
    bar.setAttribute('role', 'group');
    bar.setAttribute('aria-label', 'Filter the reviews');
    bar.appendChild(el('span', 'rv-filters-label', 'Find families like yours:'));
    var status = el('p', 'rv-status');
    status.setAttribute('aria-live', 'polite');
    var grid = el('div', 'rv-grid');
    var chips = [];
    var current = 'all';
    var made = [];

    // Only offer "Read the whole review" where the clamp actually hid words. Measured again
    // once the web font lands and on resize, because both change where the clamp falls.
    function measure() {
      made.forEach(function (c) {
        if (!c.node.classList.contains('is-open')) c.more.hidden = c.quote.scrollHeight <= c.quote.clientHeight + 2;
      });
    }
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(measure);
    var resizeTimer;
    window.addEventListener('resize', function () { clearTimeout(resizeTimer); resizeTimer = setTimeout(measure, 150); });

    function render() {
      var f = FILTERS.filter(function (x) { return x.key === current; })[0];
      var shown = f.test ? list.filter(f.test) : list;
      grid.textContent = '';
      made = shown.map(function (r) { var c = card(r); grid.appendChild(c.node); return c; });
      measure();
      status.textContent = current === 'all'
        ? 'Showing all ' + shown.length + ' reviews.'
        : 'Showing ' + shown.length + ' ' + NOUN[current] + '.';
      chips.forEach(function (c) { c.setAttribute('aria-pressed', String(c.getAttribute('data-key') === current)); });
    }

    FILTERS.forEach(function (f) {
      var n = f.test ? list.filter(f.test).length : list.length;
      if (!n) return;
      var b = el('button', 'rv-chip');
      b.type = 'button';
      b.setAttribute('data-key', f.key);
      b.appendChild(document.createTextNode(f.label + ' '));
      b.appendChild(el('span', 'rv-chip-n', String(n)));
      b.addEventListener('click', function () {
        if (current === f.key) return;
        current = f.key;
        render();
        track('rv_filter', { filter: f.key });
      });
      chips.push(b);
      bar.appendChild(b);
    });

    wall.textContent = '';
    wall.appendChild(bar);
    wall.appendChild(status);
    wall.appendChild(grid);
    render();
  }

  function start() {
    var walls = document.querySelectorAll('[data-review-wall]');
    for (var i = 0; i < walls.length; i++) mount(walls[i]);
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start);
  else start();
})();
