#!/usr/bin/env python3
"""Regenerates the REVIEWS array in js/reviews.js from data/google-reviews-*.json.

Quotes are never typed by hand: each one is copied out of the data file, whole, or cut at a
sentence end for the few that need it (EXCERPT below). The tags and the order are the only
judgment in here, and scripts/check-reviews.mjs re-proves every quote independently.

    python3 scripts/build-reviews.py   # then bump nothing: the ?v= on every page is the
                                       # file's hash, and npm test says if it is stale.
"""
import json, re, pathlib, hashlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / 'data' / 'google-reviews-2026-10-06.json'
JS = ROOT / 'js' / 'reviews.js'

# name: (age, instruments). Age only when the review itself says it: 'young' = the review
# names an age of 7 or under or says "little one" / "small kids"; 'teen' = 13 and up or
# "teenager" / "high-school"; 'adult' = the reviewer is the student. '' = the review does not
# say. Instruments only when the review names them. Order = the order shown on the page.
TAGS = [
  ('Laurissa W.', '', 'guitar'), ('Heather C.', 'young', 'piano'), ('Kimberly M.', '', 'piano'),
  ('Ashly B.', 'teen', 'piano'), ('Sammy R.', 'adult', 'guitar'), ('Melissa G.', '', 'guitar piano'),
  ('Rachel M.', 'teen', 'voice'), ('Jennifer S.', '', 'piano'), ('Emily K.', '', 'guitar'),
  ('Yessenia', 'young', 'piano'), ('Cristal C.', 'teen', 'guitar'), ('Jane A.', '', 'voice piano'),
  ('Ricardo P.', 'adult', 'voice'), ('Shakira S.', '', ''), ('Breanna Q.', 'teen', 'guitar'),
  ('Jessica S.', '', 'piano'), ('Owen L.', 'young', 'voice'), ('Gabi T.', 'young', ''),
  ('Maressah C.', 'adult', 'guitar'), ('Sarah N.', '', 'guitar voice'), ('Tammy F.', '', 'voice'),
  ('Angie G.', '', 'guitar piano'), ('Annia V.', '', ''), ('RaQuel F.', 'adult', 'voice'),
  ('Laia L.', '', 'guitar'), ('Grisiel R.', 'young', ''), ('Eva M.', '', 'piano'),
  ('Brooke P.', '', 'voice'), ('Michael T.', '', 'guitar'), ('Julissa B.', 'young', ''),
  ('Angelica K.', '', 'piano'), ('Samantha A.', '', 'guitar'), ('Andrew W.', 'adult', ''),
  ('Diana M.', '', 'guitar'), ('Jackie S.', '', 'guitar'), ('Vanessa G.', '', 'voice'),
  ('Michelle B.', '', 'guitar'), ('Victoria H.', '', 'piano'), ('Bradley H.', 'adult', 'voice'),
  ('Karla S.', '', 'guitar voice'), ('Ashley H.', '', 'guitar piano'), ('Susan W.', '', 'voice'),
  ('Donna F.', '', ''), ('Ana C.', '', ''), ('Joanna B.', '', 'voice'), ('Julie M.', '', ''),
  ('Bianca', '', 'guitar'), ('Brooklynn G.', '', ''), ('Sheila J.', '', ''), ('Amber', '', ''),
]

# Reviews quoted as their leading whole sentences only. Jennifer S.'s second paragraph has an
# em dash, which the site's guard forbids and which we may not edit out of her words, so her
# first paragraph (complete in itself) is what is shown.
EXCERPT = {'Jennifer S.': 4}

def sentences(text, n):
    # A sentence ends at . ! ? followed by whitespace. "Co." and "Mr." are not ends.
    ends = [m.end() for m in re.finditer(r'[.!?]+(?=\s)', text)
            if not re.search(r'\b(Co|Mr|Mrs|Ms|Dr)\.$', text[:m.end()])]
    return text[:ends[n - 1]]

data = {r['name']: r for r in json.loads(DATA.read_text())['reviews']}
rows = []
for name, age, inst in TAGS:
    text = data[name]['text']
    q = sentences(text, EXCERPT[name]) if name in EXCERPT else text
    rows.append({'n': name, 'q': q, 'a': age, 'i': inst})

body = ',\n'.join('    ' + json.dumps(r, ensure_ascii=False) for r in rows)
src = JS.read_text()
BEGIN, END = '// BEGIN GENERATED by scripts/build-reviews.py\n', '\n    // END GENERATED'
start = src.index(BEGIN) + len(BEGIN)
end = src.index(END, start)
JS.write_text(src[:start] + body + src[end:])
print(f'{len(rows)} reviews written; js/reviews.js v={hashlib.sha256(JS.read_bytes()).hexdigest()[:10]}')

# Point every page at the new file versions (hero-vsl.js too: same cache, same trap). /js/ is immutable for a year, so a stale ?v=
# means returning visitors keep the old reviews. npm test (check-reviews.mjs) fails on drift.
for asset in ('js/reviews.js', 'css/lp-proof.css', 'js/hero-vsl.js', 'js/headline-test.js'):
    v = hashlib.sha256((ROOT / asset).read_bytes()).hexdigest()[:10]
    pat = re.compile(r'(/' + re.escape(asset) + r'\?v=)[0-9a-f]+')
    for page in ROOT.glob('*.html'):
        t = page.read_text()
        n = pat.sub(lambda m: m.group(1) + v, t)
        if n != t:
            page.write_text(n)
